compsci-cluster-fitz-03
Sun Apr 20 03:42:44 AM EDT 2025
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Traceback (most recent call last):
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 409, in hf_raise_for_status
    response.raise_for_status()
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/whoami-v2

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1664, in whoami
    hf_raise_for_status(r)
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 481, in hf_raise_for_status
    raise _format(HfHubHTTPError, str(e), response) from e
huggingface_hub.errors.HfHubHTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/whoami-v2 (Request ID: Root=1-6804a575-285ec6c32c5b2d456337452c;2b292ac4-cb05-42dd-8f7b-de38d0f6628d)

Invalid credentials in Authorization header

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/ap794/final_project_distillLLM/venv/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/commands/huggingface_cli.py", line 57, in main
    service.run()
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/commands/user.py", line 153, in run
    login(
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 31, in inner_f
    return f(*args, **kwargs)
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/_login.py", line 126, in login
    _login(token, add_to_git_credential=add_to_git_credential)
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/_login.py", line 404, in _login
    token_info = whoami(token)
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/users/ap794/final_project_distillLLM/venv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1677, in whoami
    raise HTTPError(error_message, request=e.request, response=e.response) from e
requests.exceptions.HTTPError: Invalid user token.
srun: error: compsci-cluster-fitz-03: task 0: Exited with exit code 1
